export enum SampleTypesMapping {
  SERUMPLASMA = 1,
  PLASMA = 2,
  SERUM = 3,
  WHOLEBLOOD = 4,
  FECAL = 5,
  URINE = 6,
  QUALITYCONTROL = 7,
  ABDOMINAL = 8,
  SYNOVIAL = 9,
  CEREBROSPINAL = 10,
  THORACIC = 11,
  OTHER = 12,
  UNKNOWN = 13,
  CSF = 14,
  EAR_SWAB = 15,
  FNA = 16,
  BLOOD = 17,
}
