// tslint:disable
/**
 * IRIS API Specification
 * This document is the API specification for the IDEXX Real-time Instrument Simulator.
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export * from "./api";
export * from "./configuration";
